# -*- coding: utf-8 -*-
"""Task07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1blC8Vulaw5i_-kB1bvQ5bLUnhipfPm7x

**Task 07: Querying RDF(s)**
"""

!pip install rdflib
github_storage = "https://raw.githubusercontent.com/FacultadInformatica-LinkedData/Curso2024-2025/master/Assignment4/course_materials"

"""First let's read the RDF file"""

from rdflib import Graph, Namespace, Literal
from rdflib.namespace import RDF, RDFS
g = Graph()
g.namespace_manager.bind('ns', Namespace("http://somewhere#"), override=False)
g.namespace_manager.bind('vcard', Namespace("http://www.w3.org/2001/vcard-rdf/3.0#"), override=False)
g.parse(github_storage+"/rdf/example6.rdf", format="xml")

"""**TASK 7.1: List all subclasses of "LivingThing" with RDFLib and SPARQL**"""

# TO DO
ns = Namespace("http://somewhere#")
for s, p, o in g.triples((None, RDFS.subClassOf, ns.LivingThing)):
    print(s)
q1 = """SELECT ?s WHERE {
    ?s rdfs:subClassOf ns:LivingThing .
}"""
# Visualize the results

for r in g.query(q1):
 print(r)

"""**TASK 7.2: List all individuals of "Person" with RDFLib and SPARQL (remember the subClasses)**

"""

# TO DO
for s, p, o in g.triples((None, RDF.type, ns.Person)):
    print(s)

for subclass in g.subjects(RDFS.subClassOf, ns.Person):
    for individual in g.subjects(RDF.type, subclass):
        print(individual)

q2 = """SELECT ?s WHERE {
    {?s rdf:type ns:Person}
    UNION
    {?sub rdfs:subClassOf* ns:Person .
     ?s rdf:type ?sub}
}"""
# Visualize the results
for r in g.query(q2):
 print(r)

"""**TASK 7.3: List all individuals of just "Person" or "Animal". You do not need to list the individuals of the subclasses of person (in SPARQL only)**

"""

# TO DO
q3 = """SELECT ?individual WHERE {
    ?individual rdf:type/rdfs:subClassOf* ?type .
    FILTER (?type IN (ns:Person, ns:Animal))
}"""
# Visualize the results
for r in g.query(q3):
    print(r)

"""**TASK 7.4:  List the name of the persons who know Rocky (in SPARQL only)**"""

# TO DO
q4 = """SELECT ?name WHERE {
    ?person rdf:type ns:Person .
    ?person ns:knows ns:RockySmith .
    ?person vcard:FN ?name .
}"""
# Visualize the results
for r in g.query(q4):
  print(r)

"""**Task 7.5: List the name of those animals who know at least another animal in the graph (in SPARQL only)**"""

# TO DO
q5 = """SELECT ?name WHERE {
    ?animal rdf:type ns:Animal .
    ?animal ns:knows ?otherAnimal .
    ?otherAnimal rdf:type ns:Animal .
    ?animal vcard:FN ?name .
    FILTER (?animal != ?otherAnimal)
}"""
# Visualize the results
for r in g.query(q5):
  print(r)

"""**Task 7.6: List the age of all living things in descending order (in SPARQL only)**"""

# TO DO
q6 = """SELECT ?name ?age WHERE {
    ?livingThing rdf:type ns:LivingThing .
    ?livingThing vcard:FN ?name .
    ?livingThing ns:age ?age .
} ORDER BY DESC(?age)"""
# Visualize the results
for r in g.query(q6):
  print(r)